### PR TITLE
Allow 404 pages

### PR DESCRIPTION
**Pull request by piscis**
Add an option to move scripts to the footer on 404 pages. Hope you can integrate this.

### CODE REVIEW

**Comment by joshuadavidnelson** [comment]
Hey, @piscis, this sounds like a great idea. I should have some time to review this and get it in the plugin this week. Thanks for the contribution!

**Comment by piscis** [comment]
Hi thanks a lot it would really help us.

**Comment by joshuadavidnelson** [comment]
Hey @piscis, thanks for getting this rolling. I've added the admin settings necessary to fully incorporate the 404 support and issued a new release. The WP.org repo will be updated sometime later today with the 0.6.2 version.

**Comment by piscis** [comment]
Thank you thats really useful

**Pull request merged**
